#!/bin/bash -e
set -o errexit
set -o pipefail
set -o nounset

if ! whoami &>/dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-tfo-runner}:x:$(id -u):$(id -g):${USER_NAME:-tfo-runner} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi
mkdir -p "$TFO_GENERATION_PATH"
script="$TFO_GENERATION_PATH/$TFO_TASK.sh"
logfile="$TFO_GENERATION_PATH/$TFO_TASK.out"

inline_source="$TFO_MAIN_MODULE_ADDONS/inline-$TFO_TASK.sh"
config_map_source="$TFO_TASK_EXEC_CONFIGMAP_SOURCE_PATH/$TFO_TASK_EXEC_CONFIGMAP_SOURCE_KEY"
url_source="$TFO_TASK_EXEC_URL_SOURCE"

if [[ -f "$inline_source" ]] && [[ -s "$inline_source" ]]; then
  cp "$inline_source" "$script"
elif [[ -f "$config_map_source" ]] && [[ -s "$config_map_source" ]]; then
  cp "$config_map_source" "$script"
else
  wget -O "$script" "$url_source"
fi

cd $TFO_MAIN_MODULE || true # Doesn't exist pre-setup
chmod +x "$script"
exec "$script" "$@" | tee "$logfile"
exit ${PIPESTATUS[0]}