name: Build the script-amd64 image

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - run: pip install docker
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Log in to registry
      # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.PKG_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and push
      env:
        GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
      run: |
          cd images
          ./builder.py \
            --org galleybytes \
            --image script \
            --tag v0.0.0-alphav2 \
            --platform linux/amd64